[package]
name = "orienteering"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.48"
rand = "0.8.4"
clap = { version = "3.2.6", features = ["derive"] }
